// employee-payroll/src/app/components/display/display.component.ts
import { Component, Input, OnInit, Output } from '@angular/core';

@Component({
  selector: 'app-display',
  templateUrl: './display.component.html',
  styleUrls: ['./display.component.scss']
})
export class DisplayComponent implements OnInit {

  constructor() { }
  @Input() employeeArray = [];

  ngOnInit() {
  }
  remove(employeeId: string) {
  }

}

<table id="display" class="table">
  <tr>
    <th></th>
    <th>Name</th>
    <th>Gender</th>
    <th>Department</th>
    <th>Salary</th>
    <th>Start Date</th>
    <th>Actions</th>
  </tr>
  <tr *ngFor="let element of employeeArray">
    <td><img class="profile" src="{{element.profileUrl}}" alt=""></td>
    <td>{{element.name}}</td>
    <td>{{element.gender}}</td>
    <td>
      <div *ngFor="let dept of element.departMent" class='dept-label'>{{dept}}</div>
    </td>
    <td> ₹ {{element.salary}}</td>
    <td>{{element.startDate}}</td>
    <td><img (click)="remove(element.id)" onclick="remove(this)" src="../../../assets/icons/delete-black-18dp.svg" alt="delete">
      <img  onclick="update(this)" src="../../../assets/icons/create-black-18dp.svg" alt="edit">
    </td>
  </tr>
</table>

// employee-payroll/src/components/display/display.jsx
import React from 'react';
import './display.scss'
import deleteIcon from '../../assets/icons/delete-black-18dp.svg'
import editIcon from '../../assets/icons/create-black-18dp.svg'

const Display = (props) => {
    return (
        <table id="display" className="display">
            <tr>
                <th></th>
                <th>Name</th>
                <th>Gender</th>
                <th>Department</th>
                <th>Salary</th>
                <th>Start Date</th>
                <th>Actions</th>
            </tr>
            {
                props.employeeArray && props.employeeArray.map(element => (
                    <tr>
                        <td><img className="profile" src={element.profileUrl} alt="" /></td>
                        <td>{element.name}</td>
                        <td>{element.gender}</td>
                        <td>
                            {
                                element.departMent.map(dept => (
                                    <div className='dept-label'>{dept}</div>
                                ))
                            }

                        </td>
                        <td> ₹ {element.salary}</td>
                        <td>{element.startDate}</td>
                        <td><img onClick="remove(element.id)" src={deleteIcon} alt="delete" />
                            <img onClick="update(element.id)" src={editIcon} alt="edit" />
                        </td>
                    </tr>
                ))
            }

        </table >
    )
}
export default Display;
