// employee-payroll/src/components/home/home.jsx
import React from 'react';
import searchIcon from '../../assets/icons/search-black-18dp.svg'
import addIcon from '../../assets/icons/add-24px.svg'
import './home.scss'
import EmployeeService from '../../services/employee-service'
import Display from '../display/display';
export default class Home extends React.Component {
    constructor(props) {
        super(props)
        this.state = {
            searchExpand: false,
            employeeArray: []
        }
        this.employeeService = new EmployeeService()

    }
    openSearch = () => {
        this.setState({ searchExpand: true })
    }
    componentDidMount() {
        this.getAllEmployee();
    }

    getAllEmployee = () => {
        this.employeeService.getAllEmployee().then(data => {
            console.log("data after get ", data.data);
            this.setState({ employeeArray: data.data })
        }).catch(err => {
            console.log("err after ", err);
        })
    }

    render() {
        return (
            <div>
                <div className="column content">
                    <div className="emp-detail">
                        <div className="detail-text">
                            Employee Details <div className="count"></div>
                        </div>
                        <div className="row center button-box">
                            <div className='search-box' onClick={this.openSearch}>
                                <input className={"input " + (this.state.searchExpand && 'input-expand')} onKeyUp="search()" type="text" placeholder="" />
                                <img className="search-icon" src={searchIcon} alt="" />
                            </div>
                            <a routerLink="payroll-form" className="add-button flex-row-center">
                                <img src={addIcon} alt="" />
          Add User</a>

                        </div>
                    </div>
                    <div className="table-main">
                        <Display employeeArray={this.state.employeeArray} />
                    </div>
                </div>
            </div>
        )
    }
}

// employee-payroll/src/app/components/home/home.component.ts
import { Component, OnInit } from '@angular/core';
import { EmployeeService } from "../../services/employee-service/employee.service";

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.scss']
})
export class HomeComponent implements OnInit {

  constructor(private emplyeeService: EmployeeService) { }
  employeeArray: Array<any> = [];

  ngOnInit() {
    this.getAllEmployee();
  }

  getAllEmployee(): void {
    this.emplyeeService.getAllEmployee().subscribe(data => {
      this.employeeArray = <any>data;
      console.log("data after getAllEmployee", this.employeeArray);

    }, err => {
      console.log("err after getAllEmployee", err);
    })
  }

}

<div>
  <header class="flex-row-center header">
    <div class="logo">
      <img src="../../../assets/images/logo.png" alt="">
      <div>
        <span class="emp-text">EMPLOYEE</span><br>
        <span class="emp-text emp-payroll">PAYROLL</span>
      </div>
    </div>
  </header>
  <div class="flex-column content">
    <div class="emp-detail">
      <div class="detail-text">
        Employee Details <div class="count">{{employeeArray?.length}}</div>
      </div>
      <!-- <button onclick="addEmployee()" class="add-button flex-row-center">
            <img src="../assets/icons/add-24px.svg" alt="">
            Add User
        </button> -->
      <a href="../pages/payroll-form.html" class="add-button flex-row-center"><img src="../assets/icons/add-24px.svg"
          alt="">
        Add User</a>

    </div>
    <div class="table-main">
        <app-display [employeeArray]="employeeArray" class="table-row" style="min-width: 100%;"></app-display>
    </div>
  </div>
</div>
