// employee-payroll/src/app/components/payroll-form/payroll-form.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormControl, FormGroup, Validators } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { EmployeeService } from 'src/app/services/employee-service/employee.service';
@Component({
  selector: 'app-payroll-form',
  templateUrl: './payroll-form.component.html',
  styleUrls: ['./payroll-form.component.scss']
})
export class PayrollFormComponent implements OnInit {
  employeeForm: any;
  departMentValue = ['HR'];
  departMentValid = true;
  employeeId: string;
  isUpdate = false;
  profileArray = [
    { url: '../../../assets/profile-images/Ellipse -3.png' },
    { url: '../../../assets/profile-images/Ellipse 1.png' },
    { url: '../../../assets/profile-images/Ellipse -8.png' },
    { url: '../../../assets/profile-images/Ellipse -7.png' }

  ]
  allDepartment = [
    'HR', 'Sales', 'Finance', 'Engineer', 'Others'
  ]
  constructor(private formBuilder: FormBuilder, private employeeService: EmployeeService,
    private router: Router, private activatedRoute: ActivatedRoute) {
    this.employeeForm = this.formBuilder.group({
      name: ['', Validators.required],
      gender: ['', Validators.required],
      departMent: [],
      salary: ['', Validators.required],
      day: ['1', Validators.required],
      month: ['Jan', Validators.required],
      year: ['2020', Validators.required],
      startDate: [''],
      notes: ['',],
      id: [''],
      profileUrl: ['', Validators.required]
    });
    this.activatedRoute.params.subscribe(data => {
      if (data && data.id) {
        this.isUpdate = true;
        this.getDataById(data.id)
      }
    })

  }

  ngOnInit() {
  }

  getChecked(name) {
    return this.departMentValue.includes(name);
  }
  onCheckChange(name) {
    let index = this.departMentValue.indexOf(name);
    this.departMentValid = true;
    if (index > -1)
      this.departMentValue.splice(index, 1)
    else
      this.departMentValue.push(name)
  }
  getErrorMessage(control: FormControl, message: string) {
    if (control.errors) {
      if (control.errors.required) {
        return message + ' is required';
      }

      if (control.errors.pattern || control.errors.whitespace) {
        return 'Invalid ' + message.toLowerCase();
      }

    }
  }

  /**
   * Marks all controls in a form group as touched
   * @param formGroup - The form group to touch
   */
  private markFormGroupTouched(formGroup: FormGroup) {
    (<any>Object).values(formGroup.controls).forEach(control => {
      control.markAsTouched();
      if (control.controls) {
        this.markFormGroupTouched(control);
      }
    });
  }
  getDataById(id): void {
    this.employeeService.getEmployee(id).subscribe(data => {
      console.log("data of employee", data);
      this.setDataToFormBuilder(data)
    }, err => {
      console.log("employee not found");
    })
  }
  setDataToFormBuilder(object): void {
    let date = object.startDate.split(" ");
    this.employeeForm.setValue({
      name: object.name,
      gender: object.gender,
      departMent: [],
      salary: object.salary,
      day: date[0],
      month: date[1],
      year: date[2],
      startDate: object.startDate,
      notes: object.notes,
      id: object.id,
      profileUrl: object.profileUrl
    });
    this.departMentValue = object.departMent;
    this.employeeId = object.id;
  }
  save(event) {
    event.preventDefault();
    console.log("save");

    if (this.departMentValue.length == 0) {
      this.departMentValid = false;
      return;
    }
    if (this.employeeForm.valid) {
      this.employeeForm.controls['departMent'].setValue(this.departMentValue)
      let startDate = `${this.employeeForm.controls['day'].value} ${this.employeeForm.controls['month'].value} ${this.employeeForm.controls['year'].value}`
      this.employeeForm.controls['startDate'].setValue(startDate)
      this.employeeForm.removeControl('day');
      this.employeeForm.removeControl('month');
      this.employeeForm.removeControl('year');

      if (this.isUpdate) {
        // this line is because when user reset the value then id is also reset 
        this.employeeForm.controls['id'].setValue(this.employeeId)
        this.employeeService.updateEmployee(this.employeeForm.value).subscribe(response => {
          console.log("response is ", response);
          this.router.navigateByUrl('')
        }, err => {

        })
      } else {
        this.employeeService.addEmployee(this.employeeForm.value).subscribe(response => {
          console.log("response is ", response);
          this.router.navigateByUrl('');
        }, err => {
        })
      }
    } else {
      this.markFormGroupTouched(this.employeeForm);
    }
  }

  /**
   * description:- to reset the form value
   */
  reset(): void {
    this.employeeForm.reset();
    this.departMentValue = [];
  }
}

<div class="main">
  <app-header></app-header>

  <div class="content">
    <form class="form" action="#" [formGroup]="employeeForm" (submit)="save($event)">
      <div class="form-head">Employee Payroll form</div>
      <div class="row">
        <label class="label text" for="name">Name</label>
        <input class="input" formControlName="name" type="text" id="name" name="name" placeholder="Your name.."
          required>
      </div>
      <div class="error" *ngIf="employeeForm.controls['name'].invalid && employeeForm.controls['name'].touched">
        {{ getErrorMessage(employeeForm.controls['name'], 'name') }} </div>
      <div class="row">
        <label class="label text" for="profileUrl">Profile image</label>
        <div class="profile-radio-button">
          <label *ngFor='let profile of profileArray'>
            <input type="radio" formControlName="profileUrl" name="profileUrl" [value]="profile.url" required>
            <img class="profile" [src]="profile.url">
          </label>
        </div>
      </div>
      <div class="error"
        *ngIf="employeeForm.controls['profileUrl'].invalid && employeeForm.controls['profileUrl'].touched">
        {{ getErrorMessage(employeeForm.controls['profileUrl'], 'profile') }} </div>
      <div class="row">
        <label class="label text" for="gender">Gender</label>
        <div>
          <input type="radio" id="male" formControlName="gender" name="gender" value="male" required>
          <label class="text" for="male">Male</label>
          <input type="radio" id="female" formControlName="gender" name="gender" value="female">
          <label class="text" for="female">Female</label>
        </div>
      </div>
      <div class="error" *ngIf="employeeForm.controls['gender'].invalid && employeeForm.controls['gender'].touched">
        {{ getErrorMessage(employeeForm.controls['gender'], 'gender') }} </div>
      <div class="row">
        <label class="label text" for="department">Department</label>
        <div>
          <span *ngFor="let item of allDepartment">
            <input class="checkbox" type="checkbox" (change)="onCheckChange(item)" [name]="item"
              [checked]="getChecked(item)" [value]="item">
            <label class="text" [for]="item">{{item}}</label>
          </span>
        </div>
      </div>
      <div class="error" *ngIf="!departMentValid">
        department is required field
      </div>
      <div class="row">
        <label class="label text" for="salary">Salary</label>
        <input class="input" type="number" formControlName="salary" id="salary" name="salary" placeholder="Salary"
          required>
      </div>
      <div class="error" *ngIf="employeeForm.controls['salary'].invalid && employeeForm.controls['salary'].touched">
        {{ getErrorMessage(employeeForm.controls['salary'], 'salary') }} </div>
      <div class="row">
        <label class="label text" for="startDate">Start Date</label>
        <div>
          <select formControlName="day" id="day" name="Day">
            <option value="1">1</option>
            <option value="2">2</option>
            <option value="3">3</option>
            <option value="4">4</option>
            <option value="5">5</option>
            <option value="6">6</option>
            <option value="7">7</option>
            <option value="8">8</option>
            <option value="9">9</option>
            <option value="10">10</option>
            <option value="11">11</option>
            <option value="12">12</option>
            <option value="13">13</option>
            <option value="14">14</option>
            <option value="15">15</option>
            <option value="16">16</option>
            <option value="17">17</option>
            <option value="18">18</option>
            <option value="19">19</option>
            <option value="20">20</option>
            <option value="21">21</option>
            <option value="22">22</option>
            <option value="23">23</option>
            <option value="24">24</option>
            <option value="25">25</option>
            <option value="26">26</option>
            <option value="27">27</option>
            <option value="28">28</option>
            <option value="29">29</option>
            <option value="30">30</option>
            <option value="31">31</option>
          </select>
          <select formControlName="month" id="month" name="Month">
            <option value="Jan">January</option>
            <option value="Feb">Febuary</option>
            <option value="March">March</option>
            <option value="April">April</option>
            <option value="May">May</option>
            <option value="June">June</option>
            <option value="July">July</option>
            <option value="Aug">August</option>
            <option value="Sept">September</option>
            <option value="Oct">October</option>
            <option value="Nov">November</option>
            <option value="Dec">December</option>
          </select>
          <select formControlName="year" id="year" name="Year">
            <option value="2020">2020</option>
            <option value="2019">2019</option>
            <option value="2018">2018</option>
            <option value="2017">2017</option>
            <option value="2016">2016</option>
          </select>
        </div>
      </div>
      <div class="error"
        *ngIf="employeeForm.controls['day'] && (employeeForm.controls['day'].invalid || employeeForm.controls['month'].invalid || employeeForm.controls['year'].invalid) && (employeeForm.controls['day'].touched || employeeForm.controls['month'].touched || employeeForm.controls['year'].touched)">
        Date is required field </div>
      <div class="row">
        <label class="label text" for="notes">Notes</label>
        <textarea formControlName="notes" id="notes" class="input" name="Notes" placeholder=""
          style="height:100px"></textarea>
      </div>

      <div class="buttonParent">
        <a routerLink="" class="resetButton button cancelButton">Cancel</a>
        <div class="submit-reset">
          <button type="submit" class="button submitButton" id="submitButton">{{ isUpdate ?'Update':'Submit'}}</button>
          <button type="button" (click)="reset()" class="resetButton button">Reset</button>
        </div>
      </div>
    </form>
  </div>
</div>

// employee-payroll/src/components/payroll-form/payroll-form.jsx
import React, { useState, useEffect } from 'react';
import profile1 from '../../assets/profile-images/Ellipse -3.png';
import profile2 from '../../assets/profile-images/Ellipse 1.png';
import profile3 from '../../assets/profile-images/Ellipse -8.png';
import profile4 from '../../assets/profile-images/Ellipse -7.png';
import './payroll-form.scss';
import Toolbar from '../header/header';
import EmployeeService from '../../services/employee-service'
import { useParams, Link, withRouter } from 'react-router-dom';

const PayrollForm = (props) => {
    let initialValue = {
        name: '',
        profileArray: [
            { url: '../../../assets/profile-images/Ellipse -3.png' },
            { url: '../../../assets/profile-images/Ellipse 1.png' },
            { url: '../../../assets/profile-images/Ellipse -8.png' },
            { url: '../../../assets/profile-images/Ellipse -7.png' }

        ],
        allDepartment: [
            'HR', 'Sales', 'Finance', 'Engineer', 'Others'
        ],
        departMentValue: [],
        gender: '',
        salary: '',
        day: '1',
        month: 'Jan',
        year: '2020',
        startDate: '',
        notes: '',
        id: '',
        profileUrl: '',
        isUpdate: false,
        error: {
            department: '',
            name: '',
            gender: '',
            salary: '',
            profileUrl: '',
            startDate: ''
        }
    }
    const [formValue, setForm] = useState(initialValue);
    const params = useParams();
    const employeeService = new EmployeeService();

    useEffect(() => {
        if (params.id) {
            getDataById(params.id);
        }
    }, [])

    const getDataById = (id) => {
        employeeService.getEmployee(id).then(data => {
            console.log("data is ", data.data);
            let obj = data.data;
            setData(obj)
        }).catch(err => {
            console.log("err is ", err);
        })
    }
    const setData = (obj) => {
        let array = obj.startDate.split(' ')
        setForm({ ...formValue, ...obj, departMentValue: obj.departMent, isUpdate: true, day: array[0], month: array[1], year: array[2] })

    }
    const changeValue = (event) => {
        setForm({ ...formValue, [event.target.name]: event.target.value })
    }

    const onCheckChange = (name) => {
        let index = formValue.departMentValue.indexOf(name);
        // setForm({ ...formValue, error: { department: 'department is not valid' } })
        let checkArray = [...formValue.departMentValue]
        if (index > -1)
            checkArray.splice(index, 1)
        else
            checkArray.push(name);
        setForm({ ...formValue, departMentValue: checkArray });
    }
    const getChecked = (name) => {
        return formValue.departMentValue && formValue.departMentValue.includes(name);
    }

    const validData = async () => {
        let isError = false;
        let error = {
            department: '',
            name: '',
            gender: '',
            salary: '',
            profileUrl: '',
            startDate: ''
        }
        if (formValue.name.length < 1) {
            error.name = 'name is required field'
            isError = true;
        }
        if (formValue.gender.length < 1) {
            error.gender = 'gender is required field'
            isError = true;
        }
        if (formValue.salary.length < 1) {
            error.salary = 'salary is required field'
            isError = true;
        }
        if (formValue.profileUrl.length < 1) {
            error.profileUrl = 'profile is required field'
            isError = true;
        }

        if (formValue.departMentValue.length < 1) {
            error.department = 'department is required field'
            isError = true;
        }
        await setForm({ ...formValue, error: error })
        return isError;


    }
    const save = async (event) => {
        event.preventDefault();
        if (await validData()) {
            console.log('error', formValue);
            return;
        }
        let object = {
            name: formValue.name,
            departMent: formValue.departMentValue,
            gender: formValue.gender,
            salary: formValue.salary,
            startDate: `${formValue.day} ${formValue.month} ${formValue.year}`,
            notes: formValue.notes,
            id: formValue.id,
            profileUrl: formValue.profileUrl,

        }




        if (formValue.isUpdate) {
            // this line is because when user reset the value then id is also reset 
            employeeService.updateEmployee(object).then(data => {
                console.log('data after update', data);
                props.history.push('')
            }).catch(err => {
                console.log("Error after update");
            })
        } else {
            employeeService.addEmployee(object).then(data => {
                console.log("data added");
                props.history.push('')
            }).catch(err => {
                console.log("err while Add");

            })
        }

    }
    /**
 * description:- to reset the form value
 */
    const reset = () => {
        setForm({ ...initialValue, id: formValue.id, isUpdate: formValue.isUpdate });

        console.log(formValue);
    }
    return (
        <div className="payroll-main">
            <Toolbar />
            <div className="content">
                <form className="form" action="#" onSubmit={save}>
                    <div className="form-head">Employee Payroll form</div>
                    <div className="row">
                        <label className="label text" htmlFor="name">Name</label>
                        <input className="input" type="text" id="name" name="name" value={formValue.name} onChange={changeValue} placeholder="Your name.." />
                    </div>
                    <div className="error" > {formValue.error.name} </div>
                    <div className="row">
                        <label className="label text" htmlFor="profileUrl">Profile image</label>
                        <div className="profile-radio-button">
                            <label >
                                <input type="radio" checked={formValue.profileUrl === '../../assets/profile-images/Ellipse -3.png'} name="profileUrl" value="../../assets/profile-images/Ellipse -3.png" onChange={changeValue} />
                                <img className="profile" src={profile1} alt="profile" />
                            </label>
                            <label >
                                <input type="radio" name="profileUrl" checked={formValue.profileUrl === '../../assets/profile-images/Ellipse 1.png'} value="../../assets/profile-images/Ellipse 1.png" onChange={changeValue} />
                                <img className="profile" src={profile2} alt="profile" />
                            </label>
                            <label >
                                <input type="radio" name="profileUrl" checked={formValue.profileUrl === '../../assets/profile-images/Ellipse -8.png'} value="../../assets/profile-images/Ellipse -8.png" onChange={changeValue} />
                                <img className="profile" src={profile3} alt="profile" />
                            </label>
                            <label >
                                <input type="radio" name="profileUrl" checked={formValue.profileUrl === '../../assets/profile-images/Ellipse -7.png'} value="../../assets/profile-images/Ellipse -7.png" onChange={changeValue} />
                                <img className="profile" src={profile4} alt="profile" />
                            </label>

                        </div>
                    </div>
                    <div className="error" > {formValue.error.profileUrl} </div>
                    <div className="row">
                        <label className="label text" htmlFor="gender">Gender</label>
                        <div>
                            <input type="radio" id="male" checked={formValue.gender === 'male'} onChange={changeValue} name="gender" value="male" />
                            <label className="text" htmlFor="male">Male</label>
                            <input type="radio" id="female" checked={formValue.gender === 'female'} onChange={changeValue} name="gender" value="female" />
                            <label className="text" htmlFor="female">Female</label>
                        </div>
                    </div>
                    <div className="error" > {formValue.error.gender} </div>

                    <div className="row">
                        <label className="label text" htmlFor="department">Department</label>
                        <div>
                            {formValue.allDepartment.map(item => (
                                <span key={item}>
                                    <input className="checkbox" type="checkbox" onChange={() => onCheckChange(item)} name={item}
                                        checked={getChecked(item)} value={item} />
                                    <label className="text" htmlFor={item}>{item}</label>
                                </span>
                            ))}

                        </div>
                    </div>
                    <div className="error" > {formValue.error.department} </div>


                    <div className="row">
                        <label className="label text" htmlFor="salary">Salary</label>
                        <input className="input" type="number" onChange={changeValue} id="salary" value={formValue.salary} name="salary" placeholder="Salary"
                        />
                    </div>
                    <div className="error" > {formValue.error.salary} </div>


                    <div className="row">
                        <label className="label text" htmlFor="startDate">Start Date</label>
                        <div>
                            <select value={formValue.day} onChange={changeValue} id="day" name="day">
                                <option value="1">1</option>
                                <option value="2">2</option>
                                <option value="3">3</option>
                                <option value="4">4</option>
                                <option value="5">5</option>
                                <option value="6">6</option>
                                <option value="7">7</option>
                                <option value="8">8</option>
                                <option value="9">9</option>
                                <option value="10">10</option>
                                <option value="11">11</option>
                                <option value="12">12</option>
                                <option value="13">13</option>
                                <option value="14">14</option>
                                <option value="15">15</option>
                                <option value="16">16</option>
                                <option value="17">17</option>
                                <option value="18">18</option>
                                <option value="19">19</option>
                                <option value="20">20</option>
                                <option value="21">21</option>
                                <option value="22">22</option>
                                <option value="23">23</option>
                                <option value="24">24</option>
                                <option value="25">25</option>
                                <option value="26">26</option>
                                <option value="27">27</option>
                                <option value="28">28</option>
                                <option value="29">29</option>
                                <option value="30">30</option>
                                <option value="31">31</option>
                            </select>
                            <select value={formValue.month} onChange={changeValue} id="month" name="month">
                                <option value="Jan">January</option>
                                <option value="Feb">Febuary</option>
                                <option value="March">March</option>
                                <option value="April">April</option>
                                <option value="May">May</option>
                                <option value="June">June</option>
                                <option value="July">July</option>
                                <option value="Aug">August</option>
                                <option value="Sept">September</option>
                                <option value="Oct">October</option>
                                <option value="Nov">November</option>
                                <option value="Dec">December</option>
                            </select>
                            <select value={formValue.year} onChange={changeValue} id="year" name="year">
                                <option value="2020">2020</option>
                                <option value="2019">2019</option>
                                <option value="2018">2018</option>
                                <option value="2017">2017</option>
                                <option value="2016">2016</option>
                            </select>
                        </div>
                    </div>
                    <div className="error" > {formValue.error.startDate} </div>

                    <div className="row">
                        <label className="label text" htmlFor="notes">Notes</label>
                        <textarea onChange={changeValue} id="notes" value={formValue.notes} className="input" name="notes" placeholder=""
                            style={{ height: '100%' }}></textarea>
                    </div>

                    <div className="buttonParent">
                        <Link to="" className="resetButton button cancelButton">Cancel</Link>

                        <div className="submit-reset">
                            <button type="submit" className="button submitButton" id="submitButton">{formValue.isUpdate ? 'Update' : 'Submit'}</button>
                            <button type="button" onClick={reset} className="resetButton button">Reset</button>
                        </div>
                    </div >
                </form >
            </div >
        </div >
    )
}
export default withRouter(PayrollForm);
